#!/bin/bash

folder="${HOME}/Pictures/wallpapers"
pic=$(ls $folder/* | shuf -n1)

# values for picture-options: ‘none’, ‘wallpaper’, ‘centered’, ‘scaled’, ‘stretched’, ‘zoom’, ‘spanned’
gsettings set org.gnome.desktop.background picture-options 'wallpaper'
gsettings set org.gnome.desktop.background picture-uri "file://$pic"
gsettings set org.gnome.desktop.background picture-uri-dark "file://$pic"
